name: Unzip and Process Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in root directory
      run: ls -alh

    - name: Install unzip
      run: sudo apt-get install unzip

    - name: Unzip files
      run: unzip ChatGPT-Midjourney-RocketAI-main.zip -d extracted_files/

    - name: List extracted files
      run: ls -alh extracted_files/
