name: Unzip and Process Files

on:
  push:
    branches:
      - main  # 当推送到主分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get install unzip

    - name: Unzip files
      run: unzip path/to/your/file.zip -d path/to/extract/

    - name: Do something with the extracted files
      run: |
        # 在这里添加处理解压后文件的步骤
        ls path/to/extract/
